services:
  php:
    build:
      context:                .
    container_name:           eleave-php
    restart:                  unless-stopped
    ports:
      - '80:80'
    volumes:
      - ./:/var/www/html/
    networks:
      - eleave

  db:
    image:                    mysql:26.7.0
    container_name:           eleave-db
    restart:                  unless-stopped
    ports:
      - '3306:3306'
    environment:
        MYSQL_DATABASE:       eleave
        MYSQL_ROOT_PASSWORD:  root
        SERVICE_NAME:         mysql
    volumes:
      - ./database/eleave.sql:/docker-entrypoint-initdb.d/eleave.sql
    networks:
      - eleave
    command:                  ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']

  phpmyadmin:
      depends_on:
        - db
      image:                  phpmyadmin:5.2.3-apache
      container_name:         eleave-phpmyadmin
      restart:                unless-stopped
      ports:
        - '8080:80'
      environment:
        PMA_HOSTS:            db
      networks:
        - eleave
  mailpit:
      image:                  axllent/mailpit:v1.31.2
      container_name:         eleave-mailpit
      restart:                unless-stopped
      ports:
        - "1025:1025"
        - "8025:8025"
      networks:
        - eleave

networks:
  eleave:
    driver:                   bridge
